### ISSUE TITLE
Light should be 850nm, not 810nm

### ISSUE THREAD

**Issue by ChrisGaddes** [sharpe5/red-light-therapy#1]
First off, this is super helpful, thanks! I ordered the 900W panel from Sungrow and look forward to using it.

Unless I am mistaken, the Novothor and the panel you purchase from Alibaba use 660nm and 850nm light, not the 660nm and 810nm you mention in your posts. Just thought you might want to know.

**Comment by sharpe5** [comment]
You are absolutely correct. I actually noticed this a few days ago, it was in my queue of things to do.

The NovoThor is indeed 660nm and 850nm. The Thor Laser handheld unit is 810nm for the 200mW laser, and 850nm for the 69-diode LED probe.

The optical window in human tissue is wide enough so that anything between 810nm and 850nm will do the job.

If you havn't read Red Light Therapy by Ari Whitten, it's worth it to understand the science behind how it works. There is also some great info on www.NovoThor.com.
